In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r'C:\IT_vedant\Machine Learning\Automobile_data_Lab_4.csv')

In [3]:
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [4]:
df["normalized-losses"].replace("?",np.nan,inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22808\1267431917.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["normalized-losses"].replace("?",np.nan,inplace=True)

0      NaN
1      NaN
2      NaN
3      164
4      164
      ...
200     95
201     95
202     95
203     95
204     95
Name: normalized-losses, Length: 205, dtype: str

In [5]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [6]:
df["normalized-losses"] = pd.to_numeric(
    df["normalized-losses"],
    errors="coerce"
)

m=df["normalized-losses"].mean()
print("mean of normalized-losses:",m)
df["normalized-losses"].fillna(m,inplace=True)

mean of normalized-losses: 122.0

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22808\1832944611.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["normalized-losses"].fillna(m,inplace=True)

0      122.0
1      122.0
2      122.0
3      164.0
4      164.0
       ...
200     95.0
201     95.0
202     95.0
203     95.0
204     95.0
Name: normalized-losses, Length: 205, dtype: float64

In [7]:
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [8]:
#replace ? with null values in "horsepower" column permanently
df["horsepower"].replace("?",np.nan,inplace=True)
#change the datatype of df["horsepower"] column from object to float
#permanently
df["horsepower"]=df["horsepower"].astype("float")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22808\33509820.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["horsepower"].replace("?",np.nan,inplace=True)

ValueError: could not convert string to float: '?'

In [ ]:
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [ ]:
m = df["horsepower"].mean()
print("Mean of horsepower : ",m)
df["horsepower"].fillna(m,inplace=True)

Mean of horsepower :  104.25615763546799

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10200\1339838895.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["horsepower"].fillna(m,inplace=True)

0      111.0
1      111.0
2      154.0
3      102.0
4      115.0
       ...
200    114.0
201    160.0
202    134.0
203    106.0
204    114.0
Name: horsepower, Length: 205, dtype: float64

In [ ]:
df["horsepower"] = df["horsepower"].replace("?",np.nan)
df["horsepower"] = df["horsepower"].astype(float)
df["horsepower"].unique()

array([111., 154., 102., 115., 110., 140., 160., 101., 121., 182.,  48.,
        70.,  68.,  88., 145.,  58.,  76.,  60.,  86., 100.,  78.,  90.,
       176., 262., 135.,  84.,  64., 120.,  72., 123., 155., 184., 175.,
       116.,  69.,  55.,  97., 152., 200.,  95., 142., 143., 207., 288.,
        nan,  73.,  82.,  94.,  62.,  56., 112.,  92., 161., 156.,  52.,
        85., 114., 162., 134., 106.])

In [ ]:
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [ ]:
m=df["horsepower"].mean()
print("Mean of horsepower : ",m)
df["horsepower"].fillna(m,inplace=True)

Mean of horsepower :  104.25615763546799

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10200\1164251145.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["horsepower"].fillna(m,inplace=True)

0      111.0
1      111.0
2      154.0
3      102.0
4      115.0
       ...
200    114.0
201    160.0
202    134.0
203    106.0
204    114.0
Name: horsepower, Length: 205, dtype: float64

In [ ]:
df_num=df.select_dtypes(["int64","float64"])#hold to int and float type data 
df_cat=df.select_dtypes(object)#hold object type data

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10200\2520888041.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_cat=df.select_dtypes(object)#hold object type data

In [ ]:
from sklearn.preprocessing import LabelEncoder
for col in df_cat :
    le=LabelEncoder() #create the object of LabelEncoder class
    df_cat[col]=le.fit_transform(df_cat[col])

In [ ]:
df_cat.head()

   make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [ ]:
df_new=pd.concat([df_num,df_cat],axis=1) #axis=1 column wise
df_new.head()

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,price,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,3,NaN,64.1,48.8,130,111.0,21,27,13495,0,1,0,2,0,0
1,3,NaN,64.1,48.8,130,111.0,21,27,16500,0,1,0,2,0,0
2,1,NaN,65.5,52.4,152,154.0,19,26,16500,0,1,2,2,0,5
3,2,164.0,66.2,54.3,109,102.0,24,30,13950,1,1,3,1,0,3
4,2,164.0,66.4,54.3,136,115.0,18,22,17450,1,1,3,0,0,3

In [ ]:
X=df_new.drop("price",axis=1) #apart from price, all columns hold in X variable
Y=df_new["price"] #output variables

In [ ]:
print("Shape of X : ",X.shape)

Shape of X :  (205, 14)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,
                                              random_state=1)

In [ ]:
X_train.shape,X_test.shape

((143, 14), (62, 14))

In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [ ]:
X_train

array([[ 1.69785729,         nan,  0.12469565, ...,  1.17275014,
        -0.14638501,  0.00639503],
       [-1.42488988,         nan,  0.21756793, ...,  1.17275014,
        -0.14638501, -2.73707423],
       [-0.64420309, -1.20514298, -1.12908013, ..., -2.35784501,
        -0.14638501,  0.00639503],
       ...,
       [ 1.69785729,  0.62849447,  2.07501352, ...,  1.17275014,
        -0.14638501,  1.83537454],
       [ 0.91717049, -1.14502372, -1.03620785, ..., -2.35784501,
        -0.14638501,  0.92088479],
       [-0.64420309, -0.45365222, -0.38610189, ..., -0.59254744,
        -0.14638501,  0.00639503]], shape=(143, 14))

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr=LinearRegression()

In [ ]:
lr.fit(X_train,Y_train)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
y_pred = lr.predict(X_test)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
y_pred[:10]

In [ ]:
lr.score(X_train,Y_train)

In [ ]:
lr.coef_

In [ ]:
lr.score(X_test,Y_test)

In [ ]:
dict={'features':X.columns,'Slope':lr.coef_}
df1=pd.DataFrame(dict)
df1

In [ ]:
from sklearn.linear_model import Lasso

In [ ]:
for i in range(200,1001,50): #start=200 stop=1001-1=1000 step=+50
    #create the object of Lasso class , passing the value of lambda
    l1=Lasso(i) #first i=200 , next i=250 ......
    #automatic write formula RSS+i*sum(abs(all coef))
    #train the model with 70% data using Lasso class , use fit() inbuilt
    #method of Lasso class
    l1.fit(X_train,Y_train)
    print("Value of Lambda : ",i)
    #check training score 
    print("Training Score : ",l1.score(X_train,Y_train))
    #check testing score
    print("Testing Score : ",l1.score(X_test,Y_test))

In [ ]:
l1.coef_

In [ ]:
df1['Slope_Lasso']=l1.coef_
df1

In [ ]:
lasso_model = Lasso(alpha= 200)

In [ ]:
lasso_model.fit(X_train, Y_train)

In [ ]:
lasso_pred = lasso_model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score 
print("MAE :", mean_absolute_error(Y_test, lasso_pred)) 
print("MSE :", mean_squared_error(Y_test, lasso_pred))
print("R² Score :", r2_score(Y_test, lasso_pred))

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
for i in range(0,51): #start=0 stop=51-1=50 step=+1
    #create the object of Ridge means L2 and passing the value of lambda 
    l2=Ridge(i)
    #train the model with 70% data using Ridge class , use fit() inbuilt
    #method of Ridge class
    l2.fit(X_train,Y_train)
    print("Value of Lambda : ",i)
    #check training score 
    print("Training Score : ",l2.score(X_train,Y_train))
    #check testing score
    print("Testing Score : ",l2.score(X_test,Y_test))

In [ ]:
l2.coef_

In [ ]:
df1['Slope_Ridge']=l2.coef_
df1

In [ ]:
ridge_model = Ridge(alpha= 12)

In [ ]:
ridge_model.fit(X_train, Y_train)

In [ ]:
ridge_pred = ridge_model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("MAE :", mean_absolute_error(Y_test, ridge_pred))
print("MSE :", mean_squared_error(Y_test, ridge_pred))
print("R² Score :", r2_score(Y_test, ridge_pred))

In [ ]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression"
    ],
    "MAE": [
        2465.395028223579,
        2346.9710123689783,
        2350.473190835319
    ],
    "MSE": [
        12262833.694863686,
        11433097.715870142,
        11380696.984090814
    ],
    "R2 Score": [
        0.7965006870725597,
        0.8102699924254559,
        0.8111395722615142
    ]
})

# Display the comparison table
comparison